name: Issue credential with invitation

trigger:
  type: api
 
input:
  type: object
  properties:
    anoncreds:
      type: object
      properties:
        credentialDefinitionId:
          description: Credential definition identifier.
          type: string
        attributes:
          type: object
    invitation:
      title: Invitation
      type: object
      description: The invitation properties.
      properties:
        createConnection:
          description: Whether to create a connection as part of the exchange. This allows to directly send messages to this connection in the future, without needing to create an out of band invitation first (see for example didcomm/requestPresentation).
          type: boolean
        alias:
          description: Alias for the connection
          type: string
        label:
          description: Label for the invitation. Will be shared with the other party.
          type: string
        imageUrl:
          description: Image url to be included in the invitation.
          type: string
    comment:
      description: An optional comment sent with the exchange to provide context. 
      type: string
  required:
    - anoncreds
    - invitation
 
actions:
  - id: createCredentialIssuanceInvitation
    name: didcomm/createCredentialIssuanceInvitation@v1
    attributes:
      anoncreds:
        credentialDefinitionId: $.input.anoncreds.credentialDefinitionId
        attributes: $.input.anoncreds.attributes
      invitation: $.input.invitation
      comment: $.input.comment
