name: Create connection and Issue credential

trigger:
  type: api

input:
  type: object
  properties:
    alias:
      type: string
    label:
      type: string
    imageUrl:
      type: string
    anoncreds:
      type: object
      properties:
        credentialDefinitionId:
          description: Credential definition identifier.
          type: string
        attributes:
          type: object
 
actions:
  # Setup the connection by showing the QR code in your client
  - id: createConnection
    name: didcomm/createConnection@v1
    attributes:
      alias: $.input.alias
      label: $.input.label
      imageUrl: $.input.imageUrl
   # Issue the employee badge
  - id: issueCredential
    name: didcomm/issueCredential@v1
    attributes:
      connectionId: $.actions.createConnection.output.connection.connectionId
      anoncreds:
        credentialDefinitionId: $.input.anoncreds.credentialDefinitionId
        attributes: $.input.anoncreds.attributes
