name: Request presentation with invitation

trigger:
  type: api

input:
  type: object
  properties:
    invitation:
      title: Invitation
      type: object
      description: The invitation properties.
      properties:
        createConnection:
          description: Whether to create a connection as part of the exchange. This allows to directly send messages to this connection in the future, without needing to create an out of band invitation first (see for example didcomm/requestPresentation).
          type: boolean
        alias:
          type: string
        label:
          type: string
        imageUrl:
          type: string
        goal:
          type: string
        goalCode:
          type: string
        invitationDid:
          type: string
    anoncreds:
      type: object
      description: The Anoncreds presentation request.
      properties:
        name:
          description: Credential name or label
          type: string
        version:
          description: Credential version
          type: string
        attributes:
          description: The requested attributes.
          type: array
          items:
            type: object
        predicates:
          description: The requested predicates.
          type: array
          items:
            type: object
        requireNonRevoked:
          description: Boolean indicator if the credential should be non-revoked.
          type: boolean
    comment:
      description: An optional comment sent with the exchange to provide context. 
      type: string
  required:
    - invitation
    - anoncreds

actions:
  - id: createPresentationRequestInvitation
    name: didcomm/createPresentationRequestInvitation@v1
    attributes:
      invitation: $.input.invitation
      anoncreds: $.input.anoncreds
      comment: $.input.comment
