name: Register credential template
 
trigger:
  type: api
 
input:
  type: 'object'
  properties:
    attrNames:
      type: array
      items:
        type: string
    name:
      type: string
    version:
      type: string
      description: Must match x.x.x or x.x (e.g. 1.0 or 1.0.0)
      default: '1.0'
    network:
      type: string
      default: 'did:web'
      description: Mainnet is only available on the paid tiers.
      enum:
        - 'did:web'       
        - 'cheqd:testnet'
        - 'cheqd:mainnet'
  required:
    - name
    - version
    - attrNames
    - network
 
actions:
  - id: createSchema
    name: anoncreds/createSchema@v1
    attributes:
      attributeNames: $.input.attrNames
      name: $.input.name
      version: $.input.version
      network: $.input.network
 
  - id: createCredentialDefinition
    name: anoncreds/createCredentialDefinition@v1
    attributes:
      schemaId: $.actions.createSchema.output.schemaId
      tag: $.input.name
