name: Create credential definition

trigger:
  type: api
 
input:
  type: "object"
  properties:
    schemaId:
      type: string
    tag:
      type: string
  required:
    - schemaId
    - tag
 
actions:
  - id: createCredentialDefinition
    name: anoncreds/createCredentialDefinition@v1
    attributes:
      schemaId: $.input.schemaId
      tag: $.input.tag
