name: Issue credential

trigger:
  type: api

input:
  type: object
  properties:
    connectionId:
      description: Connection identifier to send this credential to.
      type: string
    anoncreds:
      type: object
      properties:
        credentialDefinitionId:
          description: Credential definition identifier.
          type: string
        attributes:
          type: object
    comment:
      description: An optional comment sent with the exchange to provide context.
      type: string

  required:
    - connectionId
    - anoncreds
 
actions:
  - id: issueCredential
    name: didcomm/issueCredential@v1
    attributes:
      connectionId: $.input.connectionId
      anoncreds:
        credentialDefinitionId: $.input.anoncreds.credentialDefinitionId
        attributes: $.input.anoncreds.attributes
      comment: $.input.comment
  